<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container9xwaz1y\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container9xwaz1y/appProdProjectContainer.php') {
    touch(__DIR__.'/Container9xwaz1y.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container9xwaz1y\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container9xwaz1y\appProdProjectContainer([
    'container.build_hash' => '9xwaz1y',
    'container.build_id' => '245cd5df',
    'container.build_time' => 1610720678,
], __DIR__.\DIRECTORY_SEPARATOR.'Container9xwaz1y');
